<?php

header("Access-Control-Allow-Origin: *");

$langEN = ["You need to input a password and a username to login!",
"That user does not exist!",
"You still haven't activated your account! Check you email address and activate your account!",
"Welcome to hollywood tracker!",
"The username and / or password (is) are wrong!",
"You need to fill every field in order to register!",
"That user is already registered!",
"Registration on app and website done from ",
"Registered successfully! You will receive an email message with a link to activate your account!",
"Registered successfully, but it was not possible to send the email to activate your account! Try again later.",
"Registered successfully, but it was not possible to insert the token required to activate your account in our database!",
"Registration failed due to an error, try again later!",
"The token is empty!",
"Verified successfully",
"An error ocurred, it was not possible to update your token!",
"That token is not valid or it has already been used!",
"User deleted successfully!",
"It was not possible to delete the token!",
"Email sent successfully!",
"It was not possible to send the email! Please try again later!",
"You have to provide an id in order to proceed!",
"You need to provide a username and a type before proceeding!",
"Ok",
"Movie successfully added!",
"It was not possible to add the movie right now, try again later!",
"Tv show successfully added!",
"It was not possible to add the episode right now, try again later!",
"Book successfully added!",
"It was not possible to add the book right now, try again later!",
"Updated successfully!",
"It was not possible to update the information, try again later!",
"Deleted successfully!",
"It was not possible to delete the title right now, try again later!",
"Profile information updated successfully!",
"It was not possible to update your profile, try again later!",
"Activation email for app and site hollywood tracker",
"Hello ",
", you have registered recently in the app and site hollywood tracker ",
"Click this ",
" to activate your account!",
"Your name is: ",
"Your email is: ",
"If it was not you who registered, click ",
" here",
"Copy this link ",
" to your web browser to activate your account! ",
"copy and paste this link ",
" in your web browser.",
"If it was not you who registered, ",
"You have to provide the email you registered with, in order to recover your password!",
"The email address you provided does not exist in our database!",
"Your password recovery code is: ",
" Copy the code to the app to validate it!",
"Activation code sent successfully!",
"It was not possible to send the activation code, try again later!",
"Your account was removed successfully!",
"It was not possible to delete your account right now, please try again later!",
"You need to provide a title and a thumbnail before proceeding!",
"An error occured with the image you uploaded! Try again later.",
"Image uploaded successfully",
"Failed to upload image, try again later!",
"You need to fill all the fields before submiting a bug report!",
"Bug report ",
"from ",
"Bug report successfully sent!",
"It was not possible to send the bug report, try again later!",
"You need to provide a user id before proceeding!",
"Premium successfully purchased!",
"It was not possible to check the purchase you made, try again later!",
"It was not possible to add that movie because you have exceeded the limit for free users, buy premium to unlock!",
"It was not possible to add that tv show because you have exceeded the limit for free users, buy premium to unlock!",
"It was not possible to add that book because you have exceeded the limit for free users, buy premium to unlock!",
"Password recovery",
"Password recovery request",
"no-img",
"Premium purchased failed, the transaction's signature sent is not valid!",
    "There is already a thumbnail for that title!",
    "You need to send the original receipt!",
"You need to provide a username before proceeding!",
"The username provided exists!",
    "You need to provide an email before proceeding!",
    "That user exists, but he does not have he's google account linked!",
    "Google account linked successfully!",
    "Google account linked failed, try again later!",
    "You need to provide an email and a value before proceeding!",
    ", you have registered recently in the app and site hollywood tracker using your google account ",
    "Here is your data to login if you don't wish to use your google account anymore! We recommend that you change your data once you've entered the application in the My Profile section!",
    "Your username is: ",
    "Your password is: "];


$langPT = ["Tem de introduzir um nome de utilizador e palavra-passe para poder fazer login!",
"Esse utilizador não existe!",
"Ainda não activou a sua conta! Verifique o seu email e active a sua conta!",
"Bem-vindo ao Hollywood Tracker!",
"O nome de utilizador e / ou palavra-passe estão errados!",
"Tem de preencher todos os campos para se registar!",
"Esse utilizador já está registado!",
"Registo na aplicação e site hollywood tracker efectuado por ",
"Registo efectuado com sucesso! Irá receber um email para activar a sua conta!",
"Registado com sucesso, mas não foi possível enviar o email! Tente novamente mais tarde.",
"Registado com sucesso, mas não foi possível inserir o token!",
"Não foi possível efectuar o registo neste momento, tente novamente mais tarde!",
"O token está vazio!",
"Verificado com sucesso!",
"Ocorreu um erro não foi possível actualizar o token!",
"O token não é válido ou já foi usado!",
"Utilizador apagado com sucesso!",
"Não foi possível apagar o token!",
"Email enviado com sucesso!",
"Não foi possível enviar o email! Tente novamente mais tarde.",
"Tem de fornecer um id para poder continuar!",
"Tem de fornecer um nome de utilizador e um tipo para continuar!",
"Ok",
"Filme adicionado com sucesso!",
"Não foi possível adicionar o filme neste momento, tente novamente mais tarde!",
"Episódio adicionado com sucesso!",
"Não foi possível adicionar o episódio neste momento, tente novamente mais tarde!",
"Livro adicionado com sucesso!",
"Não foi possível adicionar o livro neste momento, tente novamente mais tarde!",
"Actualizado com sucesso!",
"Não foi possível actualizar a informação, tente novamente mais tarde!",
"Apagado com sucesso!",
"Não foi possível apagar esse título neste momento, por favor tente mais tarde!",
"Informação do perfil actualizada com sucesso!",
"Não foi possível actualizar o seu perfil, tente novamente mais tarde!",
"Email de activação para a aplicação e site hollywood tracker",
"Olá ",
", registou-se recentemente na aplicação e site hollywood tracker ",
"Clique neste ",
" para activar o seu email!",
"O seu nome é: ",
"O seu email é: ",
"Se não foi você que se registou, clique ",
" aqui",
"Copie este link ",
" para o seu navegador para activar o seu email! ",
"copie e cole este link ",
" no seu navegador.",
"Se não foi você que se registou, ",
"Tem de introduzir o email com que se registou para poder recuperar a palavra-passe!",
"O email que introduziu não se encontra na nossa base de dados!",
"O seu código de autenticação é: ",
" Copie-o para a aplicação para o validar!",
"Código de recuperação enviado com sucesso! Verifique o seu email!",
"Não foi possível enviar o código de activação, tente novamente mais tarde!",
"A sua conta foi removida com sucesso!",
"Não foi possível remover a sua conta neste momento, tente novamente mais tarde!",
"É necessário um título e uma imagem para poder prosseguir!",
"Ocorreu um problema com a imagem enviada! Tente novamente mais tarde.",
"Imagem enviada com sucesso!",
"Falhou o envio da imagem, tente novamente mais tarde!",
"Tem de preencher todos os campos antes de submeter o relatório de erros!",
"Relatório de erro ",
"de ",
"Relatório de erro enviado com sucesso!",
"Falhou o envio do relatório de erro, tente novamente mais tarde!",
"Tem de fornecer o id de utilizador antes de continuar!",
"Premium comprado com sucesso!",
"Não foi possível verificar a sua compra, tente novamente mais tarde!",
"Não é possível adicionar esse filme porque já excedeu a sua quota de filmes, compre o premium para poder continuar!",
"Não é possível adicionar essa série porque já excedeu a sua quota de séries, compre o premium para poder continuar!",
"Não é possível adicionar esse livro porque já excedeu a sua quota de livros, compre o premium para poder continuar!",
"Recuperação palavra-passe",
"Pedido de recuperação de palavra-passe",
"no-img-pt",
"Compra do premium falhou, a assinatura da transacção enviada não é válida!",
    "Já existe uma miniatura com esse nome!",
"Tem de enviar o recibo original!",
"Tem de fornecer um nome de utilizador antes de continuar!",
"Esse utilizador existe!",
    "Tem de fornecer um email antes de continuar!",
    "O utilizador existe, mas não tem a conta google associada!",
    "Conta do google associada com sucesso!",
    "Não foi possível associar a conta google, tente novamente mais tarde!",
    "Tem de fornecer um email e um valor antes de continuar!",
    ", registou-se recentemente na aplicação e site hollywood tracker usando a sua conta google ",
    "Estes são os seus dados para fazer login caso não queira usar a sua conta google! Recomendamos que altere os seus dados quando entrar na aplicação usando o menu Meu Perfil!",
    "O seu nome de utilizador é: ",
    "A sua palavra-passe é: "];

function setLangToUse($lang)
{
    global $langPT;
    global $langEN;

    switch($lang)
    {
        case "pt_AO":
        case "pt_BR":
        case "pt_CV":
        case "pt_GQ":
        case "pt_GW":
        case "pt_MO":
        case "pt_MZ":
        case "pt_PT":
        case "pt_ST":
        case "pt_TL":
            return $langPT;        
        default:
            return $langEN;
    }
}
?>